Adds chapter 10 work.
network-observability/network-observability-lab pull request #19
Opened 2024-04-12 02:45 UTC by jvanderaa

What is the difference between the chNN and chNN-completed here?

2024-04-13 09:05 UTC, davidban77 commented
The completed one has everything configured

2024-04-13 09:09 UTC, davidban77 requested changes
I think this is pretty similar to #18 in terms of purpose - I think you can move it at the root level and just call it `ch10/` - like in that PR which is moved to `ch3/`

2024-05-13 13:57 UTC, chadell commented
we shouldn't leave this unattended. Let's complete it

2024-06-18 06:43 UTC, davidban77 approved these changes

2024-06-18 06:43 UTC, merged